### ISSUE TITLE
Scrolling items in RecyclerView

### ISSUE THREAD

**Issue by emailsubjekt** [Ramotion/folding-cell-android#79]
Hi, your library is awesome however sometimes when I open an item in recyclerView and scroll down while that item is open, I run into another item that is open that hasn't yet been opened. It goes cyclically like that, if there are more items, every nth item will be open. I've been waiting months for a new version thinking you might find this happening also but there isn't one so I'm writing here in hopes I'm not the only one this is happening to. Can you please help? Thank you.

**Comment by golovin47** [comment]
Hello, @emailsubjekt. We couldn't reproduce this issue in our example app with listview. If you need to use recyclerview specifically you should understand how it recycles its views. You can put a boolean flag in item's state to check if its opened or not and set it accordingly in onBindViewHolder and by clicking this item in the list. It should resolve this issue, because it looks like recyclerview simply saves its view state and this is not what you want in this particular case.
