### ISSUE TITLE
The first flip is very big.

### ISSUE THREAD

**Issue by hisham2007** [Ramotion/folding-cell-android#8]
Thanks for great work
I run the demo on my galaxy s6 edge with Android 6
the first flip is very big. it takes the whole screen. it is not like the gif displayed in repository where flip size should match displayed layout size.
the only parameter to configure is "cell:additionalFlipsCount" which control additional flips. my issue with first flip size

**Comment by oleg-vasiliev** [comment]
You run our example of usage with listview? Is possible bug with parameter "additional flips count", what value you set? Try to remove it or set to 0.

**Comment by hisham2007** [comment]
i played with this parameter in list view example. it changes additional
flips only which already working fine. my issue with the first flip which
take the full screen and overlap other list items anove it

**Comment by oleg-vasiliev** [comment]
> ..what value you set? Try to remove it or set to 0, just for testing purposes.
this can help to exclude some cases

**Comment by hisham2007** [comment]
i removed it and tried 0 and tried 5. this affect seconf flips not first flip

**Comment by nithingkamath** [comment]
@hisham2007 Hi, I ran into the same problem today. Open cell_content_layout_layout.xml and set layout_height attributes of Imageviews or any views to your desired height and everything should be working fine. :)
Reason: Its may be because of different resolutions of images. i.e you may need to put different resolution images un drawable-hdpi,mdpi,ldpi etc.

**Comment by hisham2007** [comment]
Thanks @nithingkamath , I will try it

**Comment by anubhavmalik** [comment]
in my case it worked with additionalflipscount = 0 ...
